In [4]:
# Create an 1D array with size=12, using
# a) np.arange 
import numpy as np
a = np.array(range(1,13))
a.size

12

In [62]:
# Create an 1D array with size=12, using 
# b) np.array 
a_r = np.arange(1,13,1)
print(a_r.size)
print(a_r)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
# using the same elements create arrays with shape (3,4) , (3,4,1 ), (4,3,1),(4,1,3),(2,6)
# create them using 
# a) use brackets syntax(general way of creating)
a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
b = np.array([[[1],[2],[1],[2]],[[3],[4],[1],[2]],[[3],[4],[1],[2]]])
c = np.array([[[1],[2],[1]],[[3],[4],[2]],[[3],[4],[2]],[[3],[4],[2]]])
d = np.array([[[1,2,3]],[[2,1,3]],[[2,5,4]],[[2,2,3]]])
e = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])

In [37]:
print(a.shape)
print(a.size)
print(a.ndim)

(3, 4)
12
2


In [38]:
print(b.shape)
print(b.size)
print(b.ndim)

(3, 4, 1)
12
3


In [39]:
print(c.shape)
print(c.size)
print(c.ndim)

(4, 3, 1)
12
3


In [40]:
print(d.shape)
print(d.size)
print(d.ndim)

(4, 1, 3)
12
3


In [41]:
print(e.shape)
print(e.size)
print(e.ndim)

(2, 6)
12
2


In [36]:
# create them using 
# b) use reshape method
e = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) # it is in shape(2,6)
print(e.reshape(6,2))
print(e.size)
print(e.ndim)

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
12
2


In [34]:
b = np.array([[[1],[2],[1],[2]],[[3],[4],[1],[2]],[[3],[4],[1],[2]]]) # it is in shape(3,4,1)
print(b.reshape(4,1,3))
print(b.size)
print(b.ndim)

[[[1 2 1]]

 [[2 3 4]]

 [[1 2 3]]

 [[4 1 2]]]
12
3


In [45]:
# create full array shape (9*9) with element 9 ,zero arrays shape (2,3,4), ones array shape (4,3,2)
# a) using general syntax
array_9 = np.array([[9, 9, 9 ,9, 9, 9, 9 ,9 ,9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9],[9, 9, 9, 9, 9, 9, 9, 9, 9]])
print(array_9)


[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [51]:
z = np.array([[[0, 0, 0, 0],[0, 0, 0, 0],[0, 0, 0, 0]],[[0, 0, 0 ,0],[0, 0, 0, 0],[0, 0, 0, 0]]])

print(z.shape)  

(2, 3, 4)


In [53]:
x = np.array([[[1,1],[1,1],[1,1]],[[1,1],[1,1],[1,1]],[[1,1],[1,1],[1,1]],[[1,1],[1,1],[1,1]]])
x.shape

(4, 3, 2)

In [55]:
# create full array shape (9*9) with element 9 ,zero arrays shape (2,3,4), ones array shape (4,3,2)
# b) using respective functions( like full,zero,ones)


z = np.zeros((2, 3, 4))
print(z)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [57]:
p = np.ones((4,3,2))
print(p)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [58]:
y = np.full((9,9),9)
print(y)

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [65]:
# using your own examples try showing the Difference between
# a) range, arange 
a = np.array(range(1,3))
print(a.shape)
print(a.size)
# arange is a build in function ,we can use to generate the numpy array,and also it can change to float values,but
# we can't change tha range to float values
a_r = np.arange(1,13,1)
print(a_r.size)
print(a_r)


(2,)
2
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
# using your own examples try showing the Difference between
# b) linspace,arange


d = np.linspace(1,100,10)
print(d)

#  linspace allows you to specify the number of steps. arange allows you to specify the size of the steps.
a = np.arange(1,13,1)
print(a)


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
